name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出代码
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      # Step 2: 设置 Node.js 环境
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.0"

      # Step 3: 缓存 NPM 依赖
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      # Step 4: 安装依赖
      - name: Install Dependencies
        run: npm install

      # Step 5: 安装 Hexo 和 Algolia 插件
      - name: Install Hexo and Algolia Plugins
        run: |
          npm install hexo-cli
          npm install hexo-algoliasearch

      # Step 6: 生成静态文件并上传到 Algolia
      - name: Generate and Upload to Algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        run: |
          npx hexo generate
          npx hexo algolia -n

      # Step 7: 构建（正常构建过程）
      - name: Build
        run: npm run build

      # Step 8: 上传构建成果
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
